"""配置包：集中管理全局配置与常量。"""

from .settings import (
    TENCENT_QUOTE_URL,
    TENCENT_ETF_QUOTE_URL,
    EASTMONEY_FUND_NAV_URL,
    EASTMONEY_FUND_NAV_HEADERS,
    SINA_INDEX_KLINE_URL,
    PACKAGE_DIR,
    PROJECT_ROOT,
    CACHE_DIR,
    FUND_REAL_FEE_RATE,
    RISK_FREE_RATE,
    TE_ABNORMAL_THRESHOLD,
    TD_ABNORMAL_THRESHOLD,
    NAV_INDEX_CORR_MIN,
    VALUATION_DAYS,
    STYLE_BENCHMARK_WEIGHTS,
    ensure_cache_dirs,
)

__all__ = [
    "TENCENT_QUOTE_URL",
    "TENCENT_ETF_QUOTE_URL",
    "EASTMONEY_FUND_NAV_URL",
    "EASTMONEY_FUND_NAV_HEADERS",
    "SINA_INDEX_KLINE_URL",
    "PACKAGE_DIR",
    "PROJECT_ROOT",
    "CACHE_DIR",
    "FUND_REAL_FEE_RATE",
    "RISK_FREE_RATE",
    "TE_ABNORMAL_THRESHOLD",
    "TD_ABNORMAL_THRESHOLD",
    "NAV_INDEX_CORR_MIN",
    "VALUATION_DAYS",
    "STYLE_BENCHMARK_WEIGHTS",
    "ensure_cache_dirs",
]
